--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: ActiveSupport::Multibyte::Handlers::Codepoint
includes: []

instance_methods: []

name: Codepoint
superclass: Object
