--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "key<Object>:"
    body: The key to set the parameter for.
  - !ruby/struct:SM::Flow::LI 
    label: "val<Object>:"
    body: The value of the parameter.
  type: :NOTE
full_name: Merb::Config::[]=
is_singleton: true
name: "[]="
params: (key,val)
visibility: public
