--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Returns
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "Hash:"
    body: The defaults for the config.
  type: :NOTE
full_name: Merb::Config::defaults
is_singleton: true
name: defaults
params: ()
visibility: public
