--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "key<Object>:"
    body: The key of the parameter to delete.
  type: :NOTE
full_name: Merb::Config::delete
is_singleton: true
name: delete
params: (key)
visibility: public
