--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Sets up the configuration by storing the given settings.
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "settings<Hash>:"
    body: Configuration settings to use. These are merged with the defaults.
  type: :NOTE
full_name: Merb::Config::setup
is_singleton: true
name: setup
params: (settings = {})
visibility: public
