--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Returns
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "Hash:"
    body: The config as a hash.
  type: :NOTE
full_name: Merb::Config::to_hash
is_singleton: true
name: to_hash
params: ()
visibility: public
