--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: "@configuration"
comment: 
- !ruby/struct:SM::Flow::P 
  body: Yields the configuration.
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Block parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "c<Hash>:"
    body: The configuration parameters.
  type: :NOTE
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Examples
- !ruby/struct:SM::Flow::VERB 
  body: "  Merb::Config.use do |config|\n    config[:exception_details] = false\n  end\n"
full_name: Merb::Config::use
is_singleton: true
name: use
params: () {|@configuration| ...}
visibility: public
