--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Merb::Config::ConfigBlock#method_missing
is_singleton: false
name: method_missing
params: (method, *args)
visibility: public
