--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Merb::Orms::ActiveRecord::configurations
is_singleton: true
name: configurations
params: ()
visibility: public
