--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Merb::Orms::ActiveRecord::copy_sample_config
is_singleton: true
name: copy_sample_config
params: ()
visibility: public
