:development: &defaults
  :adapter: mysql
  :database: terminus_development
  :username: terminus
  :password: terminus
  :host: localhost
  :socket: /tmp/mysql.sock
  :encoding: utf8

:test:
  <<: *defaults
  :database: terminus_test

:production:
  <<: *defaults
  :database: terminus_production
  
:rake:
  <<: *defaults
