--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Restart the Merb environment explicitly.
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "argv<String, Hash>:"
    body: The config arguments to restart Merb with. Defaults to +Merb::Config+.
  type: :NOTE
full_name: Merb::restart_environment
is_singleton: true
name: restart_environment
params: (argv={})
visibility: public
