--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Start the Merb environment, but only if it hasn't been loaded yet.
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "argv<String, Hash>:"
    body: The config arguments to start Merb with. Defaults to <tt>ARGV</tt>.
  type: :NOTE
full_name: Merb::start_environment
is_singleton: true
name: start_environment
params: (argv=ARGV)
visibility: public
