--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: run
comment: 
constants: []

full_name: Merb::BootLoader::RackUpApplication
includes: []

instance_methods: []

name: RackUpApplication
superclass: Merb::BootLoader
