--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Unpack the string at grapheme boundaries instead of codepoint boundaries
full_name: ActiveSupport::Multibyte::Handlers::UTF8Handler::g_unpack
is_singleton: true
name: g_unpack
params: (str)
visibility: protected
