--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Replaces all the non-utf-8 bytes by their iso-8859-1 or cp1252 equivalent resulting in a valid utf-8 string
full_name: ActiveSupport::Multibyte::Handlers::UTF8Handler::tidy_bytes
is_singleton: true
name: tidy_bytes
params: (str)
visibility: public
