--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Unpack the string at codepoints boundaries
full_name: ActiveSupport::Multibyte::Handlers::UTF8Handler::u_unpack
is_singleton: true
name: u_unpack
params: (str)
visibility: protected
