--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: DB2::Environment
includes: 
- !ruby/object:RI::IncludedModule 
  name: DB2Util
instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: data_sources
name: Environment
superclass: Object
