--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: ActiveSupport::Multibyte::Handlers::EncodingError
includes: []

instance_methods: []

name: EncodingError
superclass: ArgumentError
